### ISSUE TITLE
Puudub MUUDA nupp peale projekti lõpetamist

### ISSUE THREAD

**Issue by merilyh** [centre-for-educational-technology/ELU#101]
![eluveeb](https://user-images.githubusercontent.com/30046732/28054105-5869652c-661c-11e7-973d-5a0cfc485499.png)

**Comment by GlebRed** [comment]
See on seotud sellega, et kasutaja merilyh@tlu.ee ei osale selles projektis. "Muuda" nupp on nähtav juhendav tudengile, kes vaatab projekti, milles ta osaleb (projekti liige).
