### ISSUE TITLE
ELUveebi teavitused

### ISSUE THREAD

**Issue by merilyh** [centre-for-educational-technology/ELU#102]
1. Me sooviksime, et meile ELU koordinaatoritele tuleks teavitus, kui ka õppejõud lisab projekti. Hetkel tuleb teavitus ainult siis, kui tudeng lisab. 
2. Kui tudeng registreerib ennast ELU projekti gmaili konto kaudu ja õpib TLUs siis tuleb tal nimekiri TLU erialadest kust ta peab valima enda eriala. Kui aga projekti registreerib tudeng väljastpoolt meie ülikooli siis peaks olema seal juures ka lahter: muu, kuhu ta saab kirjutada mis eriala ta õpib. 

Aitäh!

**Comment by sanderaido** [comment]
1. punkti teise poole kohta - sellele google'i vormile ei ole meil kuidagi võimalik ligi pääseda. Kui see salvestab tulemused Google Sheet'i, siis seal on võimalus aktiveerida meiliteavitus ( Tools>Notification) , kui keegi vormile ridu lisab.
