### ISSUE TITLE
Statistika õpilaste järgi 

### ISSUE THREAD

**Issue by sanderaido** [centre-for-educational-technology/ELU#105]
.csv fail

**Comment by merilyh** [comment]
Tere!
Kindlasti lisada juurde ka projektiga liitunud üliõpilaste erialad (meil oleks seda statistikat vaja esitleda uue nädala alguses ehk see muudatus on kriitiline!). Ootame antud statisikat juba muudetud kujul ka .csv failis üliõpilaste järgi nagu rääkisime. 
Aitäh!

**Comment by sanderaido** [comment]
2 eraldi statistikat, üks TLÜ kontodega õpilaste jaoks (et hiljem ÕIS'i importida) ja teine muude õpilaste kohta (käsitsi sisestamiseks)
