### ISSUE TITLE
Õpilaste automaatne grupeerimine projektiga liitumisel

### ISSUE THREAD

**Issue by sanderaido** [centre-for-educational-technology/ELU#106]
Tingimused:

- max 3 sama eriala õpilast ühes grupis
- max 8 õpilast grupis
- max 3 gruppi

Kui projektis on juba nii palju õpilasi, et uus õpilane ei mahu antud tingimustesse, kuvatakse talle "Liitu projektiga" nupu asemel kiri "Kahjuks on projektis juba kohad täietud"

Õppejõul on vajadusel võimalik käsitsi lisada neljas grupp, kuid seda ei arvestata liitumise valideerimisel (ainult õppejõud saab siia käsitsi õpilasi paigutada ning seeläbi vabastada kohti algses kolmes grupis).

"Kasutajad mis ei kuulu rühmadesse" bloki võib siis uutel projektidel muutmisvaatest ära peita (vanadel kus võib veel ilma grupita õpilasi olla, võib nad seal kuvada)

**Comment by Aetm** [comment]
Mis ajaks saab see arendus valmis?
