### ISSUE TITLE
"Muuda" nupp projekti vaate päises kõigile nähtavaks, kellel selleks õigused

### ISSUE THREAD

**Issue by sanderaido** [centre-for-educational-technology/ELU#107]
Hetkel nähtav ainult juhendavale tudengile oma projektis - võiks olla ka õppejõududel enda projektidel ning adminnidel kõigill projektidel

**Comment by merilyh** [comment]
Tere!
Paluksime seda Muuda nuppu nii kiiresti kui võimalik. 

Aitäh!

**Comment by GlebRed** [comment]
Closed in bbe9479c0149ea5956f3334351f82d881867ab9b
