### ISSUE TITLE
Õppejõudude koormusarvestus veebis

### ISSUE THREAD

**Issue by merilyh** [centre-for-educational-technology/ELU#113]
[ELUkoormusarvestus.pdf](https://github.com/centre-for-educational-technology/ELU/files/1158192/ELUkoormusarvestus.pdf)

NB! Saame saata ka exceli faili kui vaja.

**Comment by tammets** [comment]
CSV

**Comment by tammets** [comment]
2 etappi - koormuse jaotamine septembris, vahenädalaks fail siseveebi jaoks.

**Comment by GlebRed** [comment]
Koormusarvestus nupp on nähtav õppejõule "Minu projektid" nimekirjas. Statistikas on ka uus nupp olemas. Nüüd on ka lisatud nupp halduritele "Kõik projektid" nimekirjas.
