### ISSUE TITLE
Automaatvastus tudengitele, kes lisavad eluveebi oma projektiidee

### ISSUE THREAD

**Issue by merilyh** [centre-for-educational-technology/ELU#115]
Peale projektiidee sisestamist kuvatakse kasutajale automaatvastus:

Hea tudeng! / Dear student!

Aitäh, oleme Sinu ELU projekti idee kätte saanud. Vaatame selle üle ja võtame Sinuga ühendust! / Thank you, we have received your ELU project idea. We will look it over and get back to you!

**Comment by sanderaido** [comment]
#102
