### ISSUE TITLE
Statistika vaates registreerinud üliõpilased KOKKU

### ISSUE THREAD

**Issue by Aetm** [centre-for-educational-technology/ELU#124]
Soovime saada statistikat hetkel käimasolevate ja avatud projektidega liitunud üliõpilaste kohta. Hetkel saame seda iga projekti kohta eraldi ning statistika vaates on kõik (ka lõppenud projektid) reas.

**Comment by tammets** [comment]
Allalaetav CSV kujul:

tudengi-nimi / e-post / eriala / projekt / juhendaja1, juhendaja2 / kaasjuhendaja1, kaasjuhendaja2
