### ISSUE TITLE
Tudengite statistika vaade "eksinud üliõpilane"

### ISSUE THREAD

**Issue by Aetm** [centre-for-educational-technology/ELU#125]
Tudengite järgi statistika vaates ilmub üliõpilaste hulka üliõpilane A. T. (_täisnimi eemaldatud_), kes on tegelikult lõppenud projekti "Kuidas töötab tuleviku kool - kuidas juhtida tulevikukooli" (Juhendaja E. E, _täisnimi eemaldatud_) üliõpilane. 

Vaatasin, et ta on projekti küll registreeritud, aga ta ei ole millegipärast esindatud allpool "Jaga liikmed rühmadesse" ülipilaste hulgas . 

Miks see tudeng ilmub käimasolevate projektide nimistusse kui aktiivse kasutajana, kes tegelikult peaks olema juba lõppenud projektide nimistus.

**Comment by tammets** [comment]
Erijuhtum on kirjeldatud eelnevalt saadetud e-kirjas.
