### ISSUE TITLE
Nõuded projektile

### ISSUE THREAD

**Issue by merilyh** [centre-for-educational-technology/ELU#146]
Millegi pärast ei saa ma ankeetide sees muuta ka lahtrit "Nõuded projektile". Sinna lahtrisse peaks tulema info: 

1. Meeskonnatöö tulemusel valminud ELU kavand;
2. Koostada meeskonnatööna ELU vahekokkuvõte etteantud vormil (semestri vahenädalaks).
3. Osaleda semestri vahenädalal toimuval tagasiside sessioonil.
4. Esitada eneserefleksioon meeskonnaliikme rolli täitmisest ja teiste liikmete panusest projekti tegevusse (esitada individuaalselt juhendajale). 
5. Koostada meeskonnatööna poster ELU projekti protsessist ja tulemustest. 
6. Osaleda meeskonnaga ELU projektide esitluspäeval ja esitada meeskonnatöö tulemusi.

**Comment by randotm** [comment]
Lisan siia ka ingliskeelse sisu.

1. Writing LIFE project plan with team members;
2. Filling out LIFE mid-term report with team members (by intermediate week);
3. Participating in feedback session at intermediate week;
4. Writing a self reflective report about your role as a team member and about others responsibilities in project work (present individually to supervisor).
5. Making a LIFE poster about your project objectives, process and outcomes.
6. Participating at LIFE projects’ presentation day and presenting outcomes of your project work with other team members.
