### ISSUE TITLE
Cleanup, et projekti gruppides kajastuks reaalne liikmete arv

### ISSUE THREAD

**Issue by romilrobtsenkov** [centre-for-educational-technology/ELU#165]

**Comment by randotm** [comment]
Found members in groups but not in project with:

SELECT groups.project_id, project_user.user_id, group_id, group_user.user_id
FROM groups
LEFT JOIN group_user ON group_user.group_id = groups.id
LEFT JOIN project_user ON project_user.user_id = group_user.user_id
WHERE project_user.user_id IS NULL 

and manually deleted them

**Comment by randotm** [comment]
Updated sql

SELECT project_user.user_id, groups.project_id, group_user.group_id, group_user.user_id
FROM group_user
RIGHT JOIN groups ON group_user.group_id = groups.id
LEFT JOIN project_user ON project_user.user_id = group_user.user_id
AND project_user.project_id = groups.project_id
WHERE project_user.user_id IS NULL
