### ISSUE TITLE
Õppeaasta valik projekti ankeedis korda

### ISSUE THREAD

**Issue by randotm** [centre-for-educational-technology/ELU#181]
Hetkel võimalik valida käesolev ja järgmine õppeaasta, teha kättesaadavaks ka varasemad.

**Comment by romilrobtsenkov** [comment]
2016/2017 sügis

**Comment by romilrobtsenkov** [comment]
<img width="789" alt="screen shot 2018-02-20 at 12 54 54" src="https://user-images.githubusercontent.com/4492641/36420300-3ccc8eb2-163d-11e8-9c61-45c0638c0f97.png">
