### ISSUE TITLE
Lõimitud valdkond -> Eriala

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/ELU#39]
Lõimitud valdkond muutub erialaks. Eriala on võimalik valida ennetava tekstisisestusega (andmed failist).

**Comment by sanderaido** [comment]
Seotud piletiga #62

**Comment by sanderaido** [comment]
Kuna see tähendab välja andmetüübi muutmist, siis mis saab eelmistest andmetest? Varasem vabateksti väli enam uue fikseeritud mitmikvalikuga ei ühildu. 
Ühe lahendusena oskan pakkuda, et muudame lahtri ära kuid jätame vana info ka nähtavale, mille alusel peab keegi (kas õppejõud ise või siis keegi halduritest) kõik projektid üle käima ja projektidele õiged erialad külge panema. Kui see tehtud, siis kustutame vana välja lõplikult.
