### ISSUE TITLE
Otsingutulemuste esitamine ja projektid otsingu lehel - tähestikulises järjekorras

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/ELU#43]
Lisaks otsingutulemustele ka otsingu lehe _listing_ vaade.

**Comment by GlebRed** [comment]
Kui projekti pealkiri vigaselt algab tühikuga, siis andmebaasi järjekorra järgi tuleb ta enne kui "A". Jutumärgid ka lähevad enne kui "A".
