### ISSUE TITLE
FAQ, inglise keelne osa WHAT

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/ELU#56]
- FAQ inglisekeelses osas eemaldada kontseptsiooni link
- Linkida ainekaardi juurde inglise keelne link (https://ois.tlu.ee/portal/page?_pageid=35,454989&_dad=portal&_schema=PORTAL&p_msg=&p_public=1&p_what=1&p_lang=EN&p_open_node2=&p_session_id=53465157&p_id=124822&p_mode=1&p_pageid=OKM_AINE_WEB_OTSING&n_disp_result=1&n_export=0&_init=1&_nextsearch=1&_nextorder=1&_orfn_1=AINER_KOOD&_ordi_1=ASC&_disp_ainer_kood=1&_where_ainer_kood=&_ainer_kood=YID&_disp_ainer_nimetus=1&_where_ainer_nimetus=&_ainer_nimetus=&_disp_ainer_nimetus_en=1&_where_ainer_nimetus_en=&_ainer_nimetus_en=&_disp_ainer_oppejoud=1&_where_ainer_oppejoud=&_ainer_oppejoud=&_where_ainer_opj_keel=&_ainer_opj_keel=&_where_ainer_kursus=&_ainer_kursus=&_where_aine_stryksus_nimetus_koodiga=&_aine_stryksus_nimetus_koodiga=&_where_tud_kava_vers=&_tud_kava_vers=&_disp_aine_opetamine_semester_id=1&_where_aine_opetamine_semester_id=&_aine_opetamine_semester_id=&_disp_ainer_eap=1&_vformaat=VFORMAAT_HTML&n_lov_offset=1&n_row_count=&n_row_pos=)

![screen shot 2017-01-20 at 13 44 14](https://cloud.githubusercontent.com/assets/380007/22149862/c0596a0e-df1e-11e6-98df-e779cb96f20f.png)

**Comment by GlebRed** [comment]
Link on vist eesti keeles

**Comment by tammets** [comment]
Keelest sõltuv link ÕIS-is puudub.
