### ISSUE TITLE
Administraator ei saa uudiseid veebilehel muuta

### ISSUE THREAD

**Issue by Aetm** [centre-for-educational-technology/ELU#58]
Administraatori poolt muudetud esilehe uudis ei muutu. Lehtede halduse kastis "Esilehe uudis" muudetud teks ei kandu peale salvestamist ("Muuda") veebi. Haldajal jääb kasti uus tekst, kuid parandatud versioon ei ilmu veebilehele.

**Comment by GlebRed** [comment]
Closed in https://github.com/centre-for-educational-technology/ELU/commit/07249ef50e5d70a8768e04efee35052d79904900
