### ISSUE TITLE
Mul on idee - ankeedi täiendused. KIIRE!

### ISSUE THREAD

**Issue by Aetm** [centre-for-educational-technology/ELU#88]
Palun lisada tudengi poolt sisestatavale projekti ankeedile järgmised täiendused:

Projekti nimi:

Idee autor:

Kirjeldus:

Interdistsiplinaarne lähenemisviis ja selle rakendamine*:  

Teaduspõhisus ja uudsus: 

Projektijuhtimise alusteadmised: 

Eriala(d):

Projekti kestus:

Õppeaasta:

Kaasjuhendaja(d):

Lisainfo: 

*probleemi mõtestamine teise eriala perspektiivist, kokkupuutepunktide otsimine, teoreetilistest/ metodoloogilistest erinevustest uute võimaluste leidmine, loovuse arendamine.

ELU projekti juhtides tuleb tagada õppeaine õpiväljundid. 
Üliõpilane: 
- kasutab meeskonnaliikmetega koostöös loodud ELU kavandis korrektselt projektijuhtimise ja interdistsiplinaarse lähenemise põhimõisteid; 
- loob ELU planeerimisel distsipliinidevahelisi seoseid ja analüüsib teiste erialade perspektiivi lähtudes püstitatud projekti lahendusvõimalustest; 
- kasutab ELU algatamisel ja elluviimisel probleemi äratundmise ja lahendamise ning ajajuhtimise oskuseid; 
- kasutab ELU elluviimise käigus omandatud uusi erialaseid teadmisi tuues ELU kaitsmisel välja nende valdkondadevahelised rakendamisvõimalused; 
- osaleb tulemuslikult meeskonnatöös ELU projekti planeerimisel, elluviimisel ja kaitsmisel; 
- analüüsib projekti edenemist ja selle tulemuslikkust, hinnates oma tegevusi kriitiliselt ja kavandades parendusmeetmeid; 
- seostab oma eriala ja laiemate ühiskondlike ning intersektoraalsete probleemidega, arutledes nende küsimuste üle erinevatel tegevuste tasanditel ja põhjendades oma arvamust; 
- analüüsib enesereflektsioonis enese kui ELU meeskonnaliikme rolli ja kohustuste täitmist ning oma panust meeskonna tegevusse.

**Comment by sanderaido** [comment]
Kas "idee autor" lahtrit on eraldi vaja? See lisatakse praegu automaatselt sisestaja ehk sisseloginud kasutaja järgi.
Lisaks näen kolme uut välja, kuidas neid kasutatakse või kus kuvatakse? Kas need jäävad näha ainult halduritele või peab need ka avalikku vaatesse lisama (kui projekt on kinnitatud ja avalikuks tehtud)?

**Comment by Aetm** [comment]
Tere,

Sellisel juhul autori rida pole vaja. Avalikus vaates mitte kuvada. Praegu tulevad need ju ainult läbi meie.

Ja see õpiväljundite osa lihtsalt ankeedi alla.

Aet
